# services:
#   carpriceprediction:
#     image: carpriceprediction
#     build: 
#       dockerfile: dockerfile

#   db:
#     image: mysql
    
services:
  web:
    build: .
    ports:
      - "8050:8050"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app

  mlflow:
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    platform: linux/amd64
    volumes:
      - mlflow:/mlflow
    ports:
      - 5000:5000

volumes:
  mlflow: